alias vim='nvim'
alias ..='cd ..'
alias vi='vim'
alias home='cd ~'
alias windows='cd /mnt/c/users/johnc/desktop'
alias :so='source ~/.bashrc && source ~/.bash_aliases'
alias sd="cd /home/ && cd \$(find * -type d | fzf)"
alias srd="cd \$(find * -type d | fzf)"
alias ofv="cd .. && vim \$(find * -type f | fzf)"
